#!/usr/bin/python3
# Author: Martin Basti
# See LICENSE file for license

import argparse
import logging
import sys
import traceback

from ipavagrant.ipaci import IPACIRunner
from ipavagrant import constants

def main():
    parser = argparse.ArgumentParser(description="")
    parser.add_argument("test_name", type=str,
                        help="Name of CI test(s) to be executed",
                        nargs='*')
    parser.add_argument("--init", action="store_true", default=False,
                        dest="initialize",
                        help="Initialize IPA CI runner in current directory")
    parser.add_argument("--debug", action="store_true", default=False,
                        dest="debug",
                        help="Enables DEBUG level logging")
    parser.add_argument("--config-topo-file", dest="config_topo_file",
                        default=None,
                        help="Path for configuration file contains tests and "
                             "topologies configuration. (default: {})".format(
                            constants.DEFAULT_TOPO_CONFIG_FILENAME
                        ))
    parser.add_argument('--export-topo-config', dest="export_topo_config",
                        default=False,
                        action="store_true", help="export current "
                        "configuration to config file (destination: "
                        "--config-topo-file)")
    parser.add_argument('--list-tests', dest="list_tests", default=False,
                        action="store_true", help="list available tests")
    # parser.add_argument("--ip-address", dest="ip_address", type=str,
    #                     metavar="IPADDR", required=True,
    #                     help="the ip address of the controller")
    # parser.add_argument("--username", dest="username", type=str,
    #                     default="vagrant", metavar="USER", help="User login "
    #                     "name to connect to controller (default: vagrant)")
    # parser.add_argument("--password", dest="password", type=str,
    #                     default="vagrant", metavar="PASSWD", help="User password "
    #                     "to connect to controller (default: vagrant)")
    args = parser.parse_args()

    if args.debug:
        logging.basicConfig(level=logging.DEBUG)
    else:
        logging.basicConfig(level=logging.INFO)

    runner = IPACIRunner(
        args.test_name,
        config_topo_file=args.config_topo_file
    )

    if args.initialize:
        if runner.is_initialized():
            raise RuntimeError("Already initialized")
        else:
            runner.initialize()
            print("Initialization done", file=sys.stderr)
            sys.exit(0)

    if args.export_topo_config:
        where = runner.topo_config.export_config()
        print("Configuration saved to", where, file=sys.stderr)
        return

    if args.list_tests:
        print("\n".join(sorted(runner.topo_config.tests.keys())))
        return

    if not runner.is_initialized():
        raise RuntimeError("IPA CI runner must be initialized first in "
                           "current directory. Please use option '--init'")

    if not args.test_name:
        RuntimeError("No tests have been specified")

    runner.run()

if __name__ == "__main__":
    try:
        main()
    except RuntimeError as e:
        logging.debug(traceback.format_exc())
        print(e, file=sys.stderr)
        sys.exit(2)
